# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TrendStory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'TrendStory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10TrendStory.proto\"T\n\x11TrendStoryRequest\x12\r\n\x05tones\x18\x01 \x01(\t\x12\x0e\n\x06themes\x18\x02 \x01(\t\x12\x0e\n\x06styles\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\"Z\n\x12TrendStoryResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x18\n\x10image_data_clean\x18\x02 \x01(\x0c\x12\x18\n\x10image_data_messy\x18\x03 \x01(\x0c\x32H\n\x11TrendStoryService\x12\x33\n\x08GetStory\x12\x12.TrendStoryRequest\x1a\x13.TrendStoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TrendStory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRENDSTORYREQUEST']._serialized_start=20
  _globals['_TRENDSTORYREQUEST']._serialized_end=104
  _globals['_TRENDSTORYRESPONSE']._serialized_start=106
  _globals['_TRENDSTORYRESPONSE']._serialized_end=196
  _globals['_TRENDSTORYSERVICE']._serialized_start=198
  _globals['_TRENDSTORYSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
